### ISSUE TITLE
Unable to use Addition/DeletionInjection (and maybe "After" injections) with a language

### ISSUE THREAD

**Issue by Kocal** [tempestphp/highlight#100]
Hi,

I'm now trying addition and deletion injections but they don't work for the following code:
```
```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
{+ pull_request_target: +}
{+   types: [opened, synchronize, reopened, ready_for_review] +}
```
`

It's rendered like this, and this is not something expected:
<img width="950" alt="image" src="https://github.com/tempestphp/highlight/assets/2103975/d31868ab-ad98-4825-b993-7e6605671123">

You can see the `$content` received by `AdditionInjection` is already highlighted, and it makes sense since this injection is executed after `(#[After])`, but the regex `(\{\+)((.|\n)*?)(\+})` can not work anymore:
<img width="970" alt="image" src="https://github.com/tempestphp/highlight/assets/2103975/d0b537a2-ad0a-499a-bdab-956b5c66fc2a">

What about moving those injections from after to before? It won't be perfect (you can see the line `5` is missing the green background behind its number), but that far better than nothing :)
<img width="956" alt="image" src="https://github.com/tempestphp/highlight/assets/2103975/923db9e0-16cc-4a2d-94e4-e28b259bf505">

WDYT?

**Comment by brendt** [comment]
I'm getting this fixed in v2. Still need to look at the weird gutter rendering, but it'll work even for After inections

**Comment by brendt** [comment]
Fixed in v2: https://github.com/tempestphp/highlight/pull/93

I plan on release it somewhere this week

**Comment by Kocal** [comment]
Thanks! :)
