### ISSUE TITLE
diff "language" support

### ISSUE THREAD

**Issue by kbond** [tempestphp/highlight#101]
I know [addition and deletions syntax](https://github.com/tempestphp/highlight?tab=readme-ov-file#supported-languages) exists and is great but what about `diff`?

This would allow nice rendering of:

```diff
- removed
+ added
```

If interested, I can try my hand at a PR.

Related, and not sure if possible, but it would be neat if you could combine `diff` with a language, for instance `php+diff`:

```php+diff
-$a = 'foo';
+$a = 'bar';
```

**Comment by brendt** [comment]
Feel free to send a PR 👍 

> Related, and not sure if possible, but it would be neat if you could combine diff with a language, for instance php+diff

Well, this is possible additions and deletions, which work multiline, as well as partial lines, which is much better than being able to only highlight full lines.
