### ISSUE TITLE
Gutter applies only on first line

### ISSUE THREAD

**Issue by bogdancondorachi** [tempestphp/highlight#104]
I can't seem to get the Gutter to work properly, it always shows only the first line as can be seen in the example below:

![image](https://github.com/tempestphp/highlight/assets/39380741/cf63f4b8-9ff7-4d46-8589-618dd6cf8ea2)
![image](https://github.com/tempestphp/highlight/assets/39380741/516b976a-a1b9-4f87-99a2-d58d4062ad3e)

```html
<pre class="hl">
  <code data-lang="PHP">
    <span class="hl-gutter ">1</span>
    <span class="hl-keyword">public</span>
    <span class="hl-keyword">class</span>
    <span class="hl-type">Foo</span>
    {}
    <span class="hl-keyword">public</span>
    <span class="hl-keyword">class</span>
    <span class="hl-type">Bar</span>
    {}
  </code>
</pre>
```

Here's also a render without the highlight applied:
```html
<pre><code>public class Foo {} public class Bar {}</code></pre>
```

**Comment by bogdancondorachi** [comment]
Solved as it wasn't caused by this package but rather by the markdown parser.

**Comment by brendt** [comment]
Fixed in https://github.com/tempestphp/highlight/releases/tag/2.3.5

**Comment by benjaminhaeberli** [comment]
Hi ! I'm trying to use tempestphp/highlight on my personel website, built with [Kirby CMS](https://getkirby.com/) (_WordPress alternative_). I have this problem when I highlight code retrieved in my [code block](https://getkirby.com/docs/reference/panel/blocks/code).

Here is what I get when I dump the value (you can see all the `\n`)
![image](https://github.com/user-attachments/assets/b4a7984b-d79c-431c-b3c5-a7b4514c31db)

But the result is this :
![image](https://github.com/user-attachments/assets/7f552a37-e220-4499-9e90-8f78c1daa19d)



And here is my code :
```php
<?php

$highlighter = new \Tempest\Highlight\Highlighter();
/** @var \Kirby\Cms\Block $block */
$code = $highlighter->withGutter()->parse($block->code()->value, 'php');

?>
<pre class="overflow-scroll text-sm">
    <code><?= $code ?></code>
</pre>
```

I also noticed that if I remove the `->withGutter()` there is still a weird space at the beginning :
![image](https://github.com/user-attachments/assets/60f48b6b-a331-4cd2-9ad2-9ada7fb757ea)
