### ISSUE TITLE
Bug: single-line docblock @return type issue

### ISSUE THREAD

**Issue by morrisonlevi** [tempestphp/highlight#122]
If you highlight something like:

```php
    /** @return K */
    function key(): mixed;
```

The docblock renders as

```html
<span class="hl-comment">/** <span class="hl-value">@return</span> <span class="hl-type">V */</span></span>
```

Focus on `<span class="hl-type">V */</span>` and notice that `*/` is part of the type.

It's not 100% clear to me that tags are _allowed_ for single-line docblocks. Single-line docblocks are allowed, I just don't know if a tag like this is technically allowed on a single line. Anyway, I was golfing because this is meant to go into a slide deck or blog post and noticed this.

**Comment by brendt** [comment]
Fixed in https://github.com/tempestphp/highlight/releases/tag/2.4.4
