### ISSUE TITLE
PHP: Heredoc with injection support

### ISSUE THREAD

**Issue by brendt** [tempestphp/highlight#16]

**Comment by brendt** [comment]
```
    return <<<HTML
    <div style="--x: {$x}; --y: {$y}; --pixel-color: {$color}"></div>
    HTML;
    ```

**Comment by hopeseekr** [comment]
Maybe genericize it like PhpStorm, where if the library recognizes "HTML" or "JS" or "SQL" and supports it, it will render inside?

The detection of HEREDOC/NOWDOC seems very untrivial to me Unless you're already doing some PHP tokenization stuff.

I wish  you all of the best.

**Comment by brendt** [comment]
Oh yes, it'll support language injection :) and it'll be super trivial to import actually, I already have it in my head, just need to write it (tomorrow :) )

**Comment by brendt** [comment]
@hopeseekr  Here it is in case you're interested: 50 lines of code :)
