### ISSUE TITLE
SQL highlighting is needed

### ISSUE THREAD

**Issue by hopeseekr** [tempestphp/highlight#22]
SQL is one of the core multi-discipline 4th generation programming languages.

I'd suggest SQL 92 as the base. Here are the keywords:

- SELECT
- FROM
- WHERE
- INSERT INTO
- UPDATE
- DELETE
- CREATE DATABASE
- ALTER DATABASE
- CREATE TABLE
- ALTER TABLE
- DROP TABLE
- CREATE INDEX
- DROP INDEX
- JOIN
- INNER JOIN
- LEFT JOIN
- RIGHT JOIN
- FULL JOIN
- UNION
- UNION ALL
- INTERSECT
- EXCEPT
- IN
- BETWEEN
- LIKE
- NOT
- AND
- OR
- AS
- DISTINCT
- GROUP BY
- ORDER BY
- HAVING
- LIMIT
- OFFSET
- CASE
- WHEN
- THEN
- ELSE
- END
- NULL
- IS NULL
- IS NOT NULL
- EXISTS
- ANY
- ALL
- SOME
- CAST
- CONVERT
- CHAR
- VARCHAR
- INT
- DATE
- TIMESTAMP

**Comment by brendt** [comment]
I've added basic support :) PRs welcome for improvements!

**Comment by hopeseekr** [comment]
You got it!!!!
