### ISSUE TITLE
Color differentiation between additions and deletions could be more pronounced

### ISSUE THREAD

**Issue by simshaun** [tempestphp/highlight#71]
I'm partially (.. mostly) color blind and the color difference here is almost indistinguishable to me:

![x](https://raw.githubusercontent.com/tempestphp/highlight/main/.github/highlight-2.png)

Something like this which has a bit more contrast is easier for me to see:

![image](https://github.com/tempestphp/highlight/assets/379519/bdab6115-e4c3-46f0-9dc7-a9e6a95815cc)

**Comment by brendt** [comment]
That's a good point! We're working on adding more themes, and I'm almost ready to merge gutter support, which will visualise additions and deletions with text as well:

<img width="697" alt="highlight-4" src="https://github.com/tempestphp/highlight/assets/6905297/c7e58442-958b-48e8-a423-3e15a394a19a">

**Comment by brendt** [comment]
With the addition of both the gutter and new themes, I'm going to close this issue for now. 

Keep in mind that if both solutions aren't sufficient, you can also override the `.hl-addition` and `.hl-deletion` classes for even more high contrast. If anyone's interested in PRing a high-contrast specific theme, then they are more than welcome to do so :)
