### ISSUE TITLE
I created an API server + Client for tempest/highlight

### ISSUE THREAD

**Issue by hopeseekr** [tempestphp/highlight#75]
Because I couldn't run `tempest/highlight` on PHP 8.2, I created a micro API server for this project. So now it can be used by any project of any language, including solely front-end JavaScript:

API Server: https://highlight.phpexperts.pro/
Git Repo: https://github.com/PHPExpertsInc/highlight.phpexperts.pro

Pure HTML5 + JS client:

```html
<link rel="stylesheet" href="https://highlight.phpexperts.pro/css/highlight-tempest.css" />
<p>This is the actual code from this page to run your own syntax highlighting in pure HTML5.</p>
<code lang="JS">
console.log("Hello, World!");
</code>
<script src="https://highlight.phpexperts.pro/js/highlight.min.js" defer="defer"></script>
```

Install via composer (for self-hosting):

    composer create-project phpexperts/tempest-highlight-api
    docker compose up -d

It uses phpexperts/dockerize, so it just works out of the box with the necessary PHP 8.3 and nginx already configured.

Detailed instructions for installing on nginx are in the README on GitHub.

PHP client (v7.2-8.3+): 

```php
  use PHPExperts\RESTSpeaker\NoAuth;
  use PHPExperts\RESTSpeaker\RESTSpeaker;

  $url = 'https://highlight.phpexperts.pro';
  $highlighter = new class(new NoAuth(), $url) extends RESTSpeaker {
      public function highlight(string $language, string $text): string
      {
          $result = $this->post('/highlight', [
              'lang' => $language,
              'text' => $text
          ]);
  
          if ($this->getLastStatusCode() === 400) {
              throw new \RuntimeException($result);
          }
  
          return $result;
      }
  };
  
  echo $highlighter->highlight('PHP', 'echo "Hello, World!\n";');
```

**Comment by aidan-casey** [comment]
Hey, @hopeseekr! I'm glad you were able to find a solution for your use case. As the issue board is here to help track actionable tasks, I'm not sure this is the best place for this, hence why I am closing this specific issue.
