### ISSUE TITLE
CSS: Cannot highlight CSS selectors probably

### ISSUE THREAD

**Issue by AbdelrhmanSaid** [tempestphp/highlight#76]
Firstly, Thanks for HUGE work, I appreciate this errors.

There's a bug parsing CSS selectors, like the attached screenshot:
![image](https://github.com/tempestphp/highlight/assets/70618755/e5f3ce29-a436-45d5-81c7-4e7839e3bcf2)

**Comment by brendt** [comment]
Fixed in https://github.com/tempestphp/highlight/releases/tag/1.0.1
