### ISSUE TITLE
Add short-hand support for aliases?

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/highlight#81]
This came to mind given #79. Given the amount of aliases you might have for a language (e.g., `js`, `javascript`, `node`), it might make sense to have a shorthand API for adding those aliases. Maybe something like:

```php
$highlighter->setLanguage(
    name: 'javascript',
    language: new JavaScriptLanguage,
    alias: ['js', 'node']
);
```

Alternatively, maybe a language could be defining some of this self itself?

Side note, [this](https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml) is the file GitHub uses.

**Comment by brendt** [comment]
Good point! It'll be tricky to add another method to the `Language` interface, but maybe we can do something with attributes. Whatever API we end up with, I agree that having aliases is a good thing.

**Comment by brendt** [comment]
The `Language` interface should change so that it can define its code and its aliases. This is a breaking change, thus I've added this issue to the v2 milestone.

**Comment by brendt** [comment]
Added in v2
