### ISSUE TITLE
JSON highlighting for null / bool / int / strings

### ISSUE THREAD

**Issue by binaryfire** [tempestphp/highlight#96]
Hi Brent. Thanks for your work on this!

Any chance you could add colorization for JSON null / bool / int / string values? This is what highlighted JSON normally looks like (taken from HighlightJS):

![image](https://github.com/tempestphp/highlight/assets/5361908/4d737740-80ca-4359-b139-789fe4e07529)
![image](https://github.com/tempestphp/highlight/assets/5361908/900eccd4-71fa-46ab-a045-1afa0309b0fb)

**Comment by brendt** [comment]
Related: #73

**Comment by NickSdot** [comment]
@brendt I am using the package since few days. Good stuff! I was wondering if it would make sense to leverage existing grammars? Might be a little bit more scalable than defining all tokens manually?

**PHP:**
https://raw.githubusercontent.com/microsoft/vscode/main/extensions/php/syntaxes/php.tmLanguage.json

**Other:**
https://github.com/microsoft/vscode/tree/main/extensions

**Comment by brendt** [comment]
I considered supporting textmate, but there already is a good implementation for it: https://github.com/spatie/shiki-php

The downside: it's very slow. So I decided to take a whole different approach with this package 👍

**Comment by NickSdot** [comment]
Fair. I totally get that! 

On a related side note. If someone is concerned about performance even with this leaner approach, then moving the actual work to persistence is might be worth to consider.

I do something like this (CommonMark):

```php

$environment = new Environment(
    // safe config
);

$environment
 ->addExtension(new CommonMarkCoreExtension())
 ->addExtension(new HighlightExtension());

$markdown = (new MarkdownConverter($environment))->convert($content)->getContent();

        $wlog = Model::create(
            $request->validated()
            + [
                'computed' => $markdown,
                'request_json' => json_encode($request->validated()),
            ]
        );

```
